{% set name = "hugo" %}
{% set version = "0.123.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fd4798ba32f0b835febc097c61850e60761a5e319bb1cce225590cc98917a975

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses

test:
  commands:
    - hugo help

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
