{% set name = "hugo" %}
{% set version = "0.151.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gohugoio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7750d644c5ea762ba400001d753a9d37dc4f1467ca470f01cffff2b2a87c9232

build:
  number: 0
  binary_relocation: false
  # Hugo binaries are statically linked on Windows, so the
  # following silences some warnings from conda-forge about
  # already exported DSOs.
  ignore_run_exports:
    - libstdcxx  # [win]
    - libwinpthread  # [win]
    - libgcc  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('go-cgo') }} >=1.24
    - go-licenses

test:
  commands:
    - hugo help
    - hugo version

about:
  home: https://gohugo.io/
  dev_url: https://github.com/gohugoio/hugo
  summary: The extended version of the Hugo static site generator – the world's fastest framework for building websites.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - moritzwilksch
    - dbast
    - agriyakhetarpal
